spring:
  application:
    name: delivery-service
  mvc:
    path match:
      matching-strategy: ant_path_matcher
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:58081}/delivery-service
    username: ${DB_USER:delivery-service}
    password: ${DB_PASS:delivery-service}
  jpa:
    database: POSTGRESQL
  flyway:
    locations: classpath:db/migration, classpath:db/data
  sql:
    init:
      platform: postgres

server:
  port: ${PORT:11000}
  shutdown: graceful
  servlet:
    context-path: /api

#2f2-pNt-j3H-Ept